markdown: kramdown
highlighter: rouge
exclude: ["*.bat","README.md", "Rakefile.rb"]
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: jucheng                                         # 博客名称
    description: "男人身上的品质就是有梦想。如果选择一种方式死去，我希望是在工作中死去。"                        # 博客描述
    title: jucheng                                         # 网页标题
    url: http://jucheng.github.io                    # 博客地址
    duoshuo:  jucheng                                         # 多说ID
    tongji: 921c5738feea196e168fcb377c0ee843             # 百度统计ID
author:
    name: jucheng                                       # 作者名称
    email: 847278378@qq.com                                 # 邮箱地址
    weibo: http://weibo.com/3100253227                    # 微博地址
    github: https://github.com/jucheng                 # GitHub地址
    logo: /res/img/logo.JPG          #logo地址
    qq: 847278378